theme = 'hugo-theme-relearn'
baseURL = 'https://prayto.day/'
# baseURL = 'http://localhost:1313'
languageCode = 'en-us'
title = 'Pray To.day'

[params]
  themeVariant = "neon"
  disableSearch = false
  disableSearchIndex = false
  disableSearchPage = false

  [markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.goldmark.extensions.extras]
  [markup.goldmark.extensions.extras.insert]
    enable = true
  [markup.goldmark.extensions.extras.mark]
    enable = true
  [markup.goldmark.extensions.extras.subscript]
    enable = true
  [markup.goldmark.extensions.extras.superscript]
    enable = true

[imageEffects]
  border = true
  lazy = true
  lightbox = true
  shadow = false

[outputs]
home = [ "HTML", "RSS"]


